/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/plugin.module';
import * as i2 from './plugin.component.ngfactory';
import * as i3 from '../../../src/app/plugin.component';
export const PluginModuleNgFactory:i0.NgModuleFactory<i1.PluginModule> = i0.ɵcmf(i1.PluginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.PluginComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i1.PluginModule,i1.PluginModule,([] as any[])),i0.ɵmpd(256,'PLUGIN_ENTRY_POINT',
              i3.PluginComponent,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29yay9tb2R1bGUtbG9hZGluZy9keW5hbWljL215cGx1Z2luL3NyYy9hcHAvcGx1Z2luLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4vc3JjL2FwcC9wbHVnaW4ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
