/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/plugin.component';
const styles_PluginComponent:any[] = ([] as any[]);
export const RenderType_PluginComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PluginComponent,data:{}});
export function View_PluginComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(0,(null as any),['\n    I am a plugin!\n    ',
      '\n    ']))],(null as any),(_ck,_v) => {
    var _co:i1.PluginComponent = _v.component;
    const currVal_0:any = _co.name;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_PluginComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'myplugin',([] as any[]),
      (null as any),(null as any),(null as any),View_PluginComponent_0,RenderType_PluginComponent)),
      i0.ɵdid(1,49152,(null as any),0,i1.PluginComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const PluginComponentNgFactory:i0.ComponentFactory<i1.PluginComponent> = i0.ɵccf('myplugin',
    i1.PluginComponent,View_PluginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29yay9tb2R1bGUtbG9hZGluZy9keW5hbWljL215cGx1Z2luL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4vc3JjL2FwcC9wbHVnaW4uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovd29yay9tb2R1bGUtbG9hZGluZy9keW5hbWljL215cGx1Z2luL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC50cy5QbHVnaW5Db21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L3dvcmsvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi9zcmMvYXBwL3BsdWdpbi5jb21wb25lbnQudHMuUGx1Z2luQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgSSBhbSBhIHBsdWdpbiFcbiAgICB7e25hbWV9fVxuICAgICIsIjxteXBsdWdpbj48L215cGx1Z2luPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7O0lBQUE7SUFBQTs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
